// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybzQfrreW17iKzBzzz8Y1BFmg4nVc4Bo',
    appId: '1:680099031728:web:43438e3d49047846e32975',
    messagingSenderId: '680099031728',
    projectId: 'finaldest-ac8e6',
    authDomain: 'finaldest-ac8e6.firebaseapp.com',
    storageBucket: 'finaldest-ac8e6.firebasestorage.app',
    measurementId: 'G-LFYTPDHCZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7j1P0kKwiBi_-Nv0UaDPfmC0oAYcS0cQ',
    appId: '1:680099031728:android:95c4695dca94b9cee32975',
    messagingSenderId: '680099031728',
    projectId: 'finaldest-ac8e6',
    storageBucket: 'finaldest-ac8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYB9Qa8Ve8lRoedh5UUfbU9ZW2NMeKcM',
    appId: '1:680099031728:ios:0c50b34386810876e32975',
    messagingSenderId: '680099031728',
    projectId: 'finaldest-ac8e6',
    storageBucket: 'finaldest-ac8e6.firebasestorage.app',
    iosBundleId: 'com.example.finaldest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxYB9Qa8Ve8lRoedh5UUfbU9ZW2NMeKcM',
    appId: '1:680099031728:ios:0c50b34386810876e32975',
    messagingSenderId: '680099031728',
    projectId: 'finaldest-ac8e6',
    storageBucket: 'finaldest-ac8e6.firebasestorage.app',
    iosBundleId: 'com.example.finaldest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAybzQfrreW17iKzBzzz8Y1BFmg4nVc4Bo',
    appId: '1:680099031728:web:91c88d7796acbfd1e32975',
    messagingSenderId: '680099031728',
    projectId: 'finaldest-ac8e6',
    authDomain: 'finaldest-ac8e6.firebaseapp.com',
    storageBucket: 'finaldest-ac8e6.firebasestorage.app',
    measurementId: 'G-P0GC4CG84Y',
  );
}
